# deploy-PROD.yml

- name: Deploy task started [PROD]
  shell: |
    export PATH=/opt/pb/bin:/opt/perf/bin:/usr/local/sbin:/usr/sbin:/sbin:.$PATH
    cd /home/search/deploy/
    ./ess_deploy.sh admin pro
  register: script_log

- debug: msg="{{ script_log.stdout }}"
