# deploy-ITG.yml

- name: Deploy task started [ITG]
  shell: |
    export PATH=/opt/pb/bin:/opt/perf/bin:/usr/local/sbin:/usr/sbin:/sbin:.$PATH
    cd /home/search/deploy/
    ./ess_deploy.sh admin itg
  register: script_log

- debug: msg="{{ script_log.stdout }}"
